### ISSUE TITLE
Compile error on Arduino 1.8,13

### ISSUE THREAD

**Issue by VisionEngineer** [Duet3D/CNC-Pendant-Firmware#3]
Hi,  getting a compile error on downloaded code 071c4fa
on 30 May 2020
 as follows:
no idea what" __attribute__" is, so cannot move forward.

sketch\PassThrough.cpp: In member function 'unsigned int PassThrough::Check(HardwareSerial&)':
PassThrough.cpp:57:9: error: expected primary-expression before '__attribute__'
         __attribute__ ((fallthrough));
         ^
exit status 1
expected primary-expression before '__attribute__'

Regards,  Robert.

**Comment by dc42** [comment]
The token in the source code is actually `__attribute__` (two leading and two trailing underscores). It compiles correctly for me using Arduino 1.8.12.

If necessary, you can remove that line. Its only purpose is to suppress the "no break at end of case" warning that may otherwise be generated.
